steps:

#
# Get a build number
#
# Cloud build doesn't use incrementing build numbers, by default, but they're often
# useful for Android builds, so these steps will read/increment/store a build number.
#
# Download the config bucket, which stores the build number.
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy_config
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
  # we use rsync and not cp so that this step doesn't fail the first time it's run
  args: ['rsync', 'gs://${_CONFIG_BUCKET}/', '/config']
  volumes:
  - name: 'config'
    path: '/config'

# Compound bash command to:
#   1. read a version
#   2. increment it
#   3. write it back to the version file
#   4. write it to the `build_env` file for use later
- name: 'gcr.io/$PROJECT_ID/tar'
  id: setup_config
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    cat /config/buildnum | awk '{$1=1+$1;print}' | tee /config/buildnum | awk '{print "BUILD_NUM="$1}'
  waitFor: ['copy_config']
  volumes:
  - name: 'config'
    path: '/config'

timeout: 1800s

