#
# Build the project
#
# In order to get the build number that we calculated earlier, we need to source the 
# build_environment.sh file *in each step it's needed* before running our build.
#
- name: 'gcr.io/$PROJECT_ID/android:28'
  id: build
  args: ["./gradlew", ":app:assembleRelease", ":app:assembleDebug", "assembleAndroidTest"]
  <<: &env
    env:
    - 'TERM=dumb'
    - 'JAVA_TOOL_OPTIONS="-Xmx4g"'
    - 'GRADLE_USER_HOME=/build_cache/.gradle'
    - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=8 -Dkotlin.incremental=false"'
    - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor: ['decrypt_secrets', 'extract_build_cache']
  volumes:
  - name: 'build_cache'
    path: '/build_cache'

timeout: 1800s

