steps:

#
# Compound bash command to:
#   1. read a version
#   2. increment it
#   3. write it back to the version file
#   4. write it to the `build_env` file for use later
- name: 'gcr.io/$PROJECT_ID/tar'
  id: setup_config
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    cat /config/buildnum | awk '{$1=1+$1;print}' | tee /config/buildnum | awk '{print "BUILD_NUM="$1}'
  waitFor: ['copy_config']
  volumes:
  - name: 'config'
    path: '/config'

timeout: 1800s

